services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_USER: postgres
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres-data: