services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale-dev
    environment:
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_USER: postgres
      POSTGRES_DB: defaultdb
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescale-data:      