apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: messaging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:latest
        ports:
        - containerPort: 9092
          name: plaintext
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka:9093"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: CLUSTER_ID
          value: "4L6g3nShT-eMCtK--X86sw"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx512M -Xms512M"
        resources:
          requests:
            memory: "768Mi"
            cpu: "250m"
          limits:
            memory: "1536Mi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 90    # Wait 90 seconds before first check
          periodSeconds: 20          # Check every 20 seconds
          timeoutSeconds: 10         # Wait 10 seconds for response
          failureThreshold: 5        # Allow 5 failures before restart
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60    # Wait 60 seconds before first check
          periodSeconds: 10          # Check every 10 seconds
          timeoutSeconds: 5          # Wait 5 seconds for response
          failureThreshold: 10       # Allow 10 failures before marking unready
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: messaging
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092