receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  
  # Add resource attributes
  resource:
    attributes:
      - key: service.namespace
        value: messaging
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: messaging
    const_labels:
      environment: development
  
  logging:
    loglevel: debug
  
  # Optional: if you want to send to other backends later
  # otlp:
  #   endpoint: "tempo:4317"
  #   tls:
  #     insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging]
