@Messaging.WebApi_HostAddress = http://localhost:5178


POST {{Messaging.WebApi_HostAddress}}/messages/information/
Accept: application/json
Content-Type: application/json

{
  "SenderId" : "the sender",
  "Content": "Hello World"
}

###

POST {{Messaging.WebApi_HostAddress}}/orders/
Accept: application/json
Content-Type: application/json

{
  "CustomerName" : "the customer",
  "Amount": 42
}

###
PUT {{Messaging.WebApi_HostAddress}}/orders/b3109a48-ec5d-4292-b985-4aa9d5dbf994/status/
Accept: application/json
Content-Type: application/json

{
  "Status":"Going Well"
}


###

POST {{Messaging.WebApi_HostAddress}}/payments/
Accept: application/json
Content-Type: application/json

{
  "OrderId" : "b3109a48-ec5d-4292-b985-4aa9d5dbf994",
  "Amount": 4242,
  "PaymentMethod":"Paypal"
}

###
