name: Build Messaging solution

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
    
      #- name: Install .NET MAUI Workload
      #  run: dotnet workload install maui-android maui-ios maui-maccatalyst maui-windows
    
      - name: Restore .NET Workloads
        run: dotnet workload restore src/Hosts/Monitoring/Maui.Prometheus.Viewer/Maui.Prometheus.Viewer.csproj
    
      - name: Restore NuGet packages
        run: dotnet restore src/Messaging.slnx --verbosity minimal

      - name: Build Messaging solution
        run: dotnet build src/Messaging.slnx --configuration Release --no-restore --verbosity minimal
   
#      - name: Run Tests from Messaging
#        run: dotnet test src/Messaging.slnx --no-build --configuration Release --logger "console;verbosity=minimal" 
      
