name: Build Messaging solution

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    # Use Ubuntu for speed on PRs, macOS for full MAUI support on main
    runs-on: ubuntu-latest
    #runs-on: ${{ github.event_name == 'pull_request' && 'ubuntu-latest' || 'macos-latest' }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    # Install workloads based on OS
    - name: Install MAUI Workloads (macOS)
      if: runner.os == 'macOS'
      run: dotnet workload install maui-android maui-ios maui-maccatalyst
    
    - name: Install MAUI Workloads (Linux - Android only)
      if: runner.os == 'Linux'
      run: dotnet workload install maui-android
    
    - name: Restore dependencies
      run: dotnet restore src/Messaging.slnx --verbosity minimal
    
    - name: Build (Full - macOS)
      if: runner.os == 'macOS'
      run: dotnet build src/Messaging.slnx --no-restore --configuration Release
    
    - name: Build (Android only - Linux)
      if: runner.os == 'Linux'
      run: |
        # Build everything except iOS targets
        dotnet build src/Messaging.slnx --no-restore --configuration Release /p:TargetFramework=net9.0-android || true
        # Or build non-MAUI projects individually
        #dotnet build src/Libraries/ --no-restore --configuration Release
        
#      - name: Run Tests from Messaging
#        run: dotnet test src/Messaging.slnx --no-build --configuration Release --logger "console;verbosity=minimal" 

      
